xcodebuild_arguments:
  - -scheme
  - HAP-Package
module: HAP
author: Bouke Haarsma
author_url: https://twitter.com/BoukeHaarsma
output: ../HAP-Docs/master
theme: fullwidth
clean: true
github_url: https://github.com/Bouke/HAP
dash_url: http://boukehaarsma.nl/HAP/HAP.xml
custom_categories:
  - name: Accessory
    children:
      - Accessory
      - AccessoryType
  - name: Service
    children:
      - Service
      - ServiceType
  - name: Characteristic
    children:
      - AnyCharacteristic
      - GenericCharacteristic
      - CharacteristicFormat
      - CharacteristicPermission
      - CharacteristicType
      - CharacteristicUnit
      - CharacteristicValueType
  - name: Characteristic Enums
    children:
      - AirQuality
      - ChargingState
      - ContactSensorState
      - CurrentDoorState
      - CurrentHeatingCoolingState
      - DiscoverBridgedAccessories
      - LockCurrentState
      - LockTargetState
      - OccupancyDetected
      - PositionState
      - SecuritySystemCurrentState
      - SecuritySystemTargetState
      - SmokeDetected
      - StatusLowBattery
      - TargetDoorState
      - TargetHeatingCoolingState
      - TemperatureDisplayUnits
  - name: Server
    children:
      - Device
      - Server
      - QRCode
  - name: Storage
    children:
      - Storage
      - FileStorage
      - MemoryStorage
  - name: HAP Encoding
    children:
      - JSONValueType
      - JSONValueTypeConvertible
      - Bool
      - Data
      - Double
      - Float
      - Int
      - RawRepresentable
      - String
