disabled_rules:
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - identifier_name
  - line_length
  - private_over_fileprivate
  - type_body_length
  - type_name
  - unused_optional_binding
included:
  - Sources
  - Tests
cyclomatic_complexity:
  error: 50
