disabled_rules:
  - function_body_length
  - private_over_fileprivate
  - todo
opt_in_rules:
  - empty_count
included:
  - Sources
  - Tests
identifier_name:
  excluded:
    - ev
    - ok
    - on
    - SESSION_KEY
    - _value
type_name:
  excluded:
    - On
