excluded:
  - Sources/HAP/Base/Generated.swift
disabled_rules:
  - function_body_length
  - private_over_fileprivate
opt_in_rules:
  - array_init
  - attributes
  - closure_spacing
  - closure_end_indentation
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - implicit_return
  - joined_default_parameter
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_parameters
  - multiple_closures_with_trailing_closure
  - no_grouping_extension
  - operator_usage_whitespace
  - operator_whitespace
  - redundant_nil_coalescing
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition
included:
  - Sources
  - Tests
identifier_name:
  excluded:
    - ev
    - fd
    - id
    - ok
    - on
    - to
    - x
    - y
    - SESSION_KEY
    - _value
    - E2BIG
type_name:
  excluded:
    - On
