public enum AccessoryType: String, Codable {
    case other = "1"
    case bridge = "2"
    case fan = "3"
    case garageDoorOpener = "4"
    case lightbulb = "5"
    case doorLock = "6"
    case outlet = "7"
    case `switch` = "8"
    case thermostat = "9"
    case sensor = "10"
    case securitySystem = "11"
    case door = "12"
    case window = "13"
    case windowCovering = "14"
    case programmableSwitch = "15"
    case rangeExtender = "16"
    case ipCamera = "17"
    case videoDoorbell = "18"
    case airPurifier = "19"
    case airHeater = "20"
    case airConditioner = "21"
    case airHumidifier = "22"
    case airDehumidifier = "23"
    case appleTV = "24"
    case speaker = "26"
    case airport = "27"
    case sprinkler = "28"
    case faucet = "29"
    case showerHead = "30"
    case television = "31"
    case targetController = "32"
    case wiFiRouter = "33"
    case audioReceiver = "34"
    case televisionSetTopBox = "35"
    case televisionStreamingStick = "36"
}

extension AccessoryType: CustomStringConvertible {
    public var description: String {
        switch self {
        case .other: return "Other"
        case .bridge: return "Bridge"
        case .fan: return "Fan"
        case .garageDoorOpener: return "Garage Door Opener"
        case .lightbulb: return "Lightbulb"
        case .doorLock: return "Door Lock"
        case .outlet: return "Outlet"
        case .`switch`: return "Switch"
        case .thermostat: return "Thermostat"
        case .sensor: return "Sensor"
        case .securitySystem: return "Security System"
        case .door: return "Door"
        case .window: return "Window"
        case .windowCovering: return "Window Covering"
        case .programmableSwitch: return "Programmable Switch"
        case .rangeExtender: return "Range Extender"
        case .ipCamera: return "IP Camera"
        case .videoDoorbell: return "Video Doorbell"
        case .airPurifier: return "Air Purifier"
        case .airHeater: return "Air Heater"
        case .airConditioner: return "Air Conditioner"
        case .airHumidifier: return "Air Humidifier"
        case .airDehumidifier: return "Air Dehumidifier"
        case .appleTV: return "Apple TV"
        case .speaker: return "Speaker"
        case .airport: return "AirPort"
        case .sprinkler: return "Sprinkler"
        case .faucet: return "Faucet"
        case .showerHead: return "Shower Head"
        case .television: return "Television"
        case .targetController: return "Target Controller"
        case .wiFiRouter: return "Wi-Fi Router"
        case .audioReceiver: return "Audio Receiver"
        case .televisionSetTopBox: return "Television Set Top Box"
        case .televisionStreamingStick: return "Television Streaming Stick"
        }
    }
}
