name: Publish Docs
on:
  push:
    branches:    
      - master
jobs:
  publish:
    name: Publish
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Publish Jazzy Docs
        uses: Steven0351/publish-jazzy-docs@v1.1.2
        with:
          personal_access_token: ${{ secrets.PAT }}
