name: Test
on:
  push:
    branches: [ master ]
  pull_request:
jobs:
  Ubuntu:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        swift: ['5.4.3', '5.5.3', '5.6.2']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Swift ${{ matrix.swift }}
        run: |
          sudo apt install libavahi-compat-libdnssd-dev
          wget --no-verbose https://swift.org/builds/swift-${{ matrix.swift }}-release/ubuntu1804/swift-${{ matrix.swift }}-RELEASE/swift-${{ matrix.swift }}-RELEASE-ubuntu18.04.tar.gz
          tar xzf swift-${{ matrix.swift }}-RELEASE-ubuntu18.04.tar.gz
          echo `pwd`/swift-${{ matrix.swift }}-RELEASE-ubuntu18.04/usr/bin >> $GITHUB_PATH
      - name: Verify Swift version
        run: swift -version | grep ${{ matrix.swift }}
      - name: Run Tests
        run: swift test -c release -Xswiftc -enable-testing
  macOS-11:
    runs-on: macos-11
    strategy:
      matrix:
        swift: ['5.4']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Swift 5.4
        run: sudo xcode-select -s /Applications/Xcode_12.5.1.app
        if: matrix.swift == '5.4'
      - name: Run Tests
        run: swift test -c release -Xswiftc -enable-testing
  macOS-12:
    runs-on: macos-12
    strategy:
      matrix:
        swift: ['5.5', '5.6', '5.7']
    steps:
      - uses: actions/checkout@v2
      - name: Setup Swift 5.5
        run: sudo xcode-select -s /Applications/Xcode_13.2.1.app
        if: matrix.swift == '5.5'
      - name: Setup Swift 5.6
        run: sudo xcode-select -s /Applications/Xcode_13.3.1.app
        if: matrix.swift == '5.6'
      - name: Setup Swift 5.7
        run: sudo xcode-select -s /Applications/Xcode_14.0.app
        if: matrix.swift == '5.7'
      - name: Run Tests
        run: swift test -c release -Xswiftc -enable-testing
